# -*- coding: utf-8 -*-
"""Untitled142.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TDCPtQEccP2npgwi7LL3I177l7VP5bZu
"""

!pip install python-telegram-bot==20.7 sentence-transformers faiss-cpu transformers pillow torch nest_asyncio

import faiss
import numpy as np
from PIL import Image
import nest_asyncio

from sentence_transformers import SentenceTransformer
from transformers import BlipProcessor, BlipForConditionalGeneration

from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, filters, ContextTypes


nest_asyncio.apply()

# =========================
# MEMORY + CACHE
# =========================
user_history = {}
cache = {}
last_caption = {}

# =========================
# DATA
# =========================
docs = [
    "Machine learning is a subset of artificial intelligence.",
    "Deep learning uses neural networks with multiple layers.",
    "Python is widely used for data science and AI.",
    "RAG combines retrieval with generation for better answers."
]

# =========================
# EMBEDDING
# =========================
embed_model = SentenceTransformer('all-MiniLM-L6-v2')
doc_embeddings = embed_model.encode(docs)

index = faiss.IndexFlatL2(len(doc_embeddings[0]))
index.add(np.array(doc_embeddings))

def retrieve(query):
    q = embed_model.encode([query])
    D, I = index.search(np.array(q), k=2)
    return [docs[i] for i in I[0]]

# =========================
# IMAGE MODEL
# =========================
processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")

def generate_caption(image_path):
    image = Image.open(image_path).convert('RGB')
    inputs = processor(image, return_tensors="pt")
    out = model.generate(**inputs)
    caption = processor.decode(out[0], skip_special_tokens=True)
    return caption

# =========================
# COMMANDS
# =========================
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "🤖 Bot Ready!\n\n"
        "/ask <query>\n"
        "Send image\n"
        "/summarize\n"
        "/history"
    )

async def ask(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.message.chat_id
    query = " ".join(context.args)

    if not query:
        await update.message.reply_text("❌ Enter query")
        return

    # Cache
    if query in cache:
        await update.message.reply_text("⚡ Cached:\n" + cache[query])
        return

    results = retrieve(query)

    # Save history
    if user_id not in user_history:
        user_history[user_id] = []
    user_history[user_id].append(query)
    user_history[user_id] = user_history[user_id][-3:]

    response = "📚 Answer:\n\n"
    for r in results:
        response += f"👉 {r}\n"

    cache[query] = response

    await update.message.reply_text(response)

# =========================
# IMAGE
# =========================
async def handle_image(update: Update, context: ContextTypes.DEFAULT_TYPE):
    photo = update.message.photo[-1]
    file = await photo.get_file()

    file_path = "image.jpg"
    await file.download_to_drive(file_path)

    caption = generate_caption(file_path)

    last_caption[update.message.chat_id] = caption

    await update.message.reply_text(f"🖼 Caption:\n{caption}")

# =========================
#  SUMMARIZE
# =========================
async def summarize(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.message.chat_id

    if user_id in last_caption:
        text = last_caption[user_id]
        summary = "📝 Summary:\n" + text[:60]
        await update.message.reply_text(summary)
    else:
        await update.message.reply_text("❌ No image to summarize")

# =========================
#  HISTORY
# =========================
async def history(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.message.chat_id

    if user_id in user_history:
        hist = user_history[user_id]
        response = "🧠 Last 3 Queries:\n\n"
        for i, q in enumerate(hist, 1):
            response += f"{i}. {q}\n"
    else:
        response = "❌ No history yet"

    await update.message.reply_text(response)

# =========================
# MAIN
# =========================
TOKEN = "8768900779:AAEQRXtbdWXMXfQ6L7W-5Gg2lRJKZoMA9v0"

app = ApplicationBuilder().token(TOKEN).build()

app.add_handler(CommandHandler("start", start))
app.add_handler(CommandHandler("ask", ask))
app.add_handler(CommandHandler("summarize", summarize))
app.add_handler(CommandHandler("history", history))
app.add_handler(MessageHandler(filters.PHOTO, handle_image))

print("🚀 Bot Running...")

await app.run_polling()

"""GenAI Telegram Bot (RAG + Vision)
 Overview
This project is a lightweight GenAI Telegram bot that supports:
- RAG-based question answering
- Image captioning
- Enhancements like caching, history, and summarization

---

 Features

- /ask → Answer queries using RAG
- Image upload → Caption generation
- /history → Last 3 queries
- /summarize → Summary of last image
- Cache → Faster repeated queries

---


- Python
- python-telegram-bot
- sentence-transformers
- FAISS
- Hugging Face (BLIP)

---

pip install python-telegram-bot sentence-transformers faiss-cpu transformers pillow torch  
python app.py  

---

Run on Colab

Install:
!pip install python-telegram-bot sentence-transformers faiss-cpu transformers pillow torch nest_asyncio  

Paste code and run

Architecture

User → Telegram → Bot → RAG / Vision Model → Response

---

 Why Local Models?

- No API cost
- Fast
- Privacy-safe

---



- /ask what is AI
- Send image → caption
- /history
- /summarize
"""